import type { Metadata } from 'next'
import { Martian_Mono, Shantell_Sans } from 'next/font/google'
import { Deck } from './deck'
import './globals.css'

const font = Shantell_Sans({
  subsets: ['latin'],
  variable: '--font-sans',
  axes: ['INFM', 'BNCE', 'SPAC'],
})

const fontMono = Martian_Mono({
  subsets: ['latin'],
  axes: ['wdth'],
  variable: '--font-mono',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${font.variable} ${fontMono.variable}`}>
        <Deck>{children}</Deck>
      </body>
    </html>
  )
}
